spring:
  devtools:
    remote:
      secret: mysecret

name: 这是yml文件中的数据


my:
    value: ${random.value}
    int: ${random.int}
    long: ${random.long}
    uuid: ${random.uuid}
    int.less.than.ten: ${random.int(10)}
    # 100前面和1000后面可以是 -，(，[ 等任意字符
    int.in.range: ${random.int-100,1000-}